### ISSUE TITLE
As a customer/visitor, I want to be able to: create an account so I can have a logged-in experience.

### ISSUE THREAD

**Issue by madeleine-lloyd-davies** [Binturong-GH/Grace-Shopper#21]
- [x] navbar should have link to log in or create new account (if user is not logged in)
- [x] link should take you to account creation page
- [x] account creation page should allow you to create new user in db and validate information, as well as immediately signing you in afterwards

**Comment by Elena-Lin-616** [comment]
I've complete the front-end and backend signup and login experience,
